import {useMemo,useState,type ReactNode} from 'react';
import {ArrowRight,Beaker,BookOpen,Check,ChevronLeft,ClipboardCheck,Clock3,Eye,FlaskConical,LockKeyhole,NotebookPen,TriangleAlert,Trophy,Flame,Activity} from 'lucide-react';
import {crackedBeam as c,scoreDiagnosis} from './case';
import {loadProgress,recordCompletion,rankFor,type Progress} from './progress';
type Screen='home'|'brief'|'investigate'|'report';
export default function App(){
 const [screen,setScreen]=useState<Screen>('home'),[reviewed,setReviewed]=useState<string[]>([]),[tests,setTests]=useState<string[]>([]),[hyp,setHyp]=useState(''),[notes,setNotes]=useState('');
 const [progress,setProgress]=useState<Progress>(()=>loadProgress()); const [savedAttempt,setSavedAttempt]=useState(false);
 const spent=useMemo(()=>c.tests.filter(t=>tests.includes(t.id)).reduce((a,t)=>a+t.cost,0),[tests]);
 const unlocked=new Set(['e1','e2','e3',...c.tests.filter(t=>tests.includes(t.id)).flatMap(t=>t.unlocks||[])]); const result=screen==='report'?scoreDiagnosis(hyp,reviewed,tests):null;
 const review=(id:string)=>setReviewed(x=>x.includes(id)?x:[...x,id]); const runTest=(id:string)=>{const t=c.tests.find(x=>x.id===id)!;if(!tests.includes(id)&&spent+t.cost<=c.budget)setTests(x=>[...x,id])};
 const submit=()=>{const r=scoreDiagnosis(hyp,reviewed,tests);if(!savedAttempt){setProgress(recordCompletion(r.total,r.iq));setSavedAttempt(true)}setScreen('report')};
 const reset=()=>{setReviewed([]);setTests([]);setHyp('');setNotes('');setSavedAttempt(false);setScreen('brief')};
 if(screen==='home')return <main className="shell"><Header/><section className="dashboard"><div><div className="eyebrow">ENGINEERING FAILURE LAB</div><h1>Good engineers solve problems.<br/><em>Great engineers understand failures.</em></h1><p>Investigate realistic engineering failures, build evidence chains, spend your test budget wisely and grow your Engineering IQ.</p></div><div className="profile-card"><small>YOUR LAB STATUS</small><strong>{rankFor(progress.iq)}</strong><div className="iq"><b>{progress.iq}</b><span>ENGINEERING IQ</span></div><div className="profile-stats"><span><Trophy/> {progress.bestScore || '—'}<small>BEST SCORE</small></span><span><Flame/> {progress.streak}<small>DAY STREAK</small></span><span><Activity/> {progress.attempts}<small>ATTEMPTS</small></span></div></div></section><section className="section-head"><div><span>ACTIVE CASE</span><h2>Continue your investigation</h2></div><small>01 CASE AVAILABLE</small></section><section className="case-card featured"><div><span className="case-code">C-001 · CIVIL · INTERMEDIATE</span><h2>The Cracked Beam</h2><p>A recently completed reinforced-concrete beam has developed significant mid-span cracking after occupancy. Determine the root cause before repair begins.</p><div className="case-meta"><span>100 IP BUDGET</span><span>~12 MIN</span><span>{progress.attempts?'BEST '+progress.bestScore+'/100':'UNSOLVED'}</span></div></div><button className="primary" onClick={()=>setScreen('brief')}>{progress.attempts?'Investigate again':'Start investigation'} <ArrowRight size={17}/></button></section><section className="locked-grid">{['Mechanical · Shaft Failure','Electrical · Motor Overheating','Computer · API Collapse'].map(x=><div className="locked" key={x}><LockKeyhole size={17}/><b>{x}</b><small>New failure case · coming next</small></div>)}</section></main>;
 if(screen==='brief')return <main className="shell"><Header/><button className="back" onClick={()=>setScreen('home')}><ChevronLeft size={16}/> Dashboard</button><section className="brief"><div className="eyebrow">{c.code} · {c.branch.toUpperCase()}</div><h1>{c.title}</h1><p className="lead">{c.briefing}</p><div className="brief-grid"><div className="panel"><h3><ClipboardCheck size={18}/> Known information</h3>{c.facts.map(x=><div className="fact" key={x}>{x}</div>)}</div><div className="panel objective"><TriangleAlert size={26}/><h3>Your assignment</h3><p>Establish the most probable root cause using the available evidence and investigation budget. Do not order every test—good engineers investigate efficiently.</p><div className="budget-big">100 <small>INVESTIGATION POINTS</small></div></div></div><button className="primary" onClick={()=>setScreen('investigate')}>Enter investigation workspace <ArrowRight size={18}/></button></section></main>;
 if(screen==='report'&&result){const answer=c.hypotheses.find(x=>x.id===c.correct)!;return <main className="shell"><Header/><section className="report"><div className="eyebrow">FAILURE INVESTIGATION REPORT · {c.code}</div><div className={'verdict '+(result.correct?'good':'bad')}><span>{result.correct?'ROOT CAUSE CONFIRMED':'DIAGNOSIS NOT SUPPORTED'}</span><strong>{result.total}</strong><small>/ 100</small></div><h1>{answer.title}</h1><p className="lead">The crack geometry is characteristic of flexural tension cracking. Reinforcement and concrete-strength checks do not support material or detailing failure, while the occupancy audit identifies an added masonry partition that increased permanent bending demand.</p><div className="score-grid"><Score n={result.diagnosisScore} max={50} label="Diagnosis"/><Score n={result.evidenceScore} max={30} label="Evidence"/><Score n={result.investigationScore} max={25} label="Efficiency"/><Score n={result.iq} label="IQ gained"/></div><div className="report-grid"><div className="panel"><h3>Engineering conclusion</h3><p>The evidence chain most strongly supports service-level flexural overstress caused by an unaccounted post-handover load. Reinforcement and material checks remove the strongest competing explanations.</p></div><div className="panel"><h3>Recommended response</h3><p>Restrict the added load, obtain a structural assessment, verify serviceability/capacity, and determine whether repair or strengthening is required before restoring occupancy.</p></div></div>{notes&&<div className="panel note-report"><h3>Your investigation note</h3><p>{notes}</p></div>}<div className="report-actions"><button className="primary" onClick={reset}>Investigate again</button><button className="ghost" onClick={()=>setScreen('home')}>Return to dashboard <ArrowRight size={16}/></button></div></section></main>}
 return <main className="workspace"><header className="work-head"><button className="icon" onClick={()=>setScreen('brief')}><ChevronLeft/></button><div><span>{c.code} · LIVE INVESTIGATION</span><b>{c.title}</b></div><div className="budget"><small>IP REMAINING</small><strong>{c.budget-spent}</strong><span>/ {c.budget}</span></div></header><div className="work-grid"><section className="column"><Title icon={<Eye/>} title="Evidence" sub={`${reviewed.length} reviewed`}/>{c.evidence.map(e=>{const open=unlocked.has(e.id);return <button key={e.id} disabled={!open} onClick={()=>review(e.id)} className={'evidence '+(reviewed.includes(e.id)?'seen':'')}><div>{open?<Eye size={16}/>:<LockKeyhole size={16}/>}<b>{e.title}</b>{reviewed.includes(e.id)&&<Check size={15}/>}</div><p>{!open?'Requires further investigation':e.detail}</p></button>})}</section><section className="column center"><Title icon={<Beaker/>} title="Technical subject" sub="RC beam · field sketch"/><Beam/><div className="observation"><span>FIELD OBSERVATION 01</span><b>Vertical cracking concentrated at mid-span</b><p>Pattern appears to initiate at the tension face. No obvious diagonal cracking at supports.</p></div><Title icon={<FlaskConical/>} title="Available tests" sub={`${spent}/${c.budget} IP spent`}/>{c.tests.map(t=>{const done=tests.includes(t.id),cant=!done&&spent+t.cost>c.budget;return <div className="test" key={t.id}><div><b>{t.title}</b><span><Clock3 size={13}/>{t.time} · {t.cost} IP</span></div><button disabled={cant||done} onClick={()=>runTest(t.id)}>{done?'Completed':'Request'}</button>{done&&<p className="test-result"><Check size={14}/>{t.result}</p>}</div>})}</section><section className="column"><Title icon={<BookOpen/>} title="Hypotheses" sub="Select one root cause"/>{c.hypotheses.map(h=><button className={'hyp '+(hyp===h.id?'selected':'')} onClick={()=>setHyp(h.id)} key={h.id}><span className="radio">{hyp===h.id&&<i/>}</span><div><b>{h.title}</b><p>{h.description}</p></div></button>)}<label className="notes"><span><NotebookPen size={15}/> Investigator notes</span><textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Record your reasoning…"/></label><button className="submit" disabled={!hyp} onClick={submit}>Submit final diagnosis <ArrowRight size={17}/></button><small className="warning">Submission ends this investigation attempt.</small></section></div></main>
}
function Header(){return <header className="header"><div className="logo"><span>F</span><b>FAIL<span>LAB</span></b></div><div className="tag">BREAK IT · DIAGNOSE IT · UNDERSTAND IT</div></header>}
function Title({icon,title,sub}:{icon:ReactNode,title:string,sub:string}){return <div className="title"><span>{icon}</span><div><b>{title}</b><small>{sub}</small></div></div>}
function Score({n,max,label}:{n:number,max?:number,label:string}){return <div><strong>{n}{max&&<small>/{max}</small>}</strong><span>{label}</span></div>}
function Beam(){return <div className="beam-wrap"><div className="load">ADDED LOAD ↓ ↓ ↓</div><div className="beam"><i/><i/><i/><i/><i/></div><div className="supports"><span>▲</span><span>▲</span></div><div className="dimension">←──────── 5.8 m SPAN ────────→</div></div>}
