import {useMemo,useState,type ReactNode} from 'react';
import {ArrowRight,Beaker,BookOpen,Check,ChevronLeft,ClipboardCheck,Clock3,Eye,FlaskConical,NotebookPen,TriangleAlert,Trophy,Flame,Activity,Target,WalletCards,ChartNoAxesCombined} from 'lucide-react';
import {cases,scoreDiagnosis,type FailureCase,type InvestigationScore} from './case';
import {caseProgress,loadProgress,rankFor,recordAttempt,solvedCount,type AttemptUpdate,type Progress} from './progress';

type Screen='home'|'brief'|'investigate'|'report';

export default function App(){
 const [screen,setScreen]=useState<Screen>('home');
 const [caseIndex,setCaseIndex]=useState(0);
 const [reviewed,setReviewed]=useState<string[]>([]);
 const [tests,setTests]=useState<string[]>([]);
 const [hyp,setHyp]=useState('');
 const [notes,setNotes]=useState('');
 const [progress,setProgress]=useState<Progress>(()=>loadProgress());
 const [attemptUpdate,setAttemptUpdate]=useState<AttemptUpdate|null>(null);
 const c=cases[caseIndex];
 const spent=useMemo(()=>c.tests.filter(t=>tests.includes(t.id)).reduce((a,t)=>a+t.cost,0),[c,tests]);
 const unlocked=new Set([...c.evidence.filter(e=>e.initial).map(e=>e.id),...c.tests.filter(t=>tests.includes(t.id)).flatMap(t=>t.unlocks||[])]);
 const result:InvestigationScore|null=screen==='report'?scoreDiagnosis(c,hyp,reviewed,tests):null;
 const cp=caseProgress(progress,c.code);

 const openCase=(i:number)=>{setCaseIndex(i);setReviewed([]);setTests([]);setHyp('');setNotes('');setAttemptUpdate(null);setScreen('brief')};
 const review=(id:string)=>setReviewed(x=>x.includes(id)?x:[...x,id]);
 const runTest=(id:string)=>{const t=c.tests.find(x=>x.id===id)!;if(!tests.includes(id)&&spent+t.cost<=c.budget)setTests(x=>[...x,id])};
 const submit=()=>{const r=scoreDiagnosis(c,hyp,reviewed,tests);const update=recordAttempt(c.code,r.total,r.baseIq,r.correct);setProgress(update.progress);setAttemptUpdate(update);setScreen('report')};
 const reset=()=>openCase(caseIndex);

 if(screen==='home')return <main className="shell"><Header/><section className="dashboard"><div><div className="eyebrow">ENGINEERING FAILURE LAB · PHASE 3</div><h1>Investigate first.<br/><em>Learn from the evidence.</em></h1><p>Each case now tracks mastery independently. Evidence is staged, investigation points matter, and your score rewards diagnosis, reasoning, test selection and efficiency — not repeated guessing.</p></div><div className="profile-card"><small>YOUR LAB STATUS</small><strong>{rankFor(progress.iq)}</strong><div className="iq"><b>{progress.iq}</b><span>ENGINEERING IQ</span></div><div className="profile-stats"><span><Trophy/> {progress.bestScore||'—'}<small>BEST SCORE</small></span><span><Flame/> {progress.streak}<small>DAY STREAK</small></span><span><Target/> {solvedCount(progress)}/{cases.length}<small>CASES SOLVED</small></span></div></div></section><section className="section-head"><div><span>FAILURE CASE LIBRARY</span><h2>Choose an investigation</h2></div><small>{String(cases.length).padStart(2,'0')} CASES AVAILABLE</small></section><section className="department-grid">{cases.map((x,i)=>{const p=caseProgress(progress,x.code);const status=p.solved?'SOLVED':p.attempts?'IN PROGRESS':'NEW';return <article className={'case-card dept-card '+(p.solved?'solved':'')} key={x.code}><div><div className="case-top"><span className="case-code">{x.code} · {x.branch.toUpperCase()}</span><span className={'status '+status.toLowerCase().replace(' ','-')}>{status}</span></div><h2>{x.title}</h2><p>{x.briefing}</p><div className="case-meta"><span>{x.difficulty.toUpperCase()}</span><span>{x.budget} IP</span><span>{p.attempts?`${p.attempts} ATTEMPT${p.attempts===1?'':'S'}`:'UNTRIED'}</span>{p.bestScore>0&&<span>BEST {p.bestScore}</span>}</div></div><button className="primary" onClick={()=>openCase(i)}>{p.attempts?'Reinvestigate':'Investigate'} <ArrowRight size={17}/></button></article>})}</section></main>;

 if(screen==='brief')return <main className="shell"><Header/><button className="back" onClick={()=>setScreen('home')}><ChevronLeft size={16}/> Case library</button><section className="brief"><div className="eyebrow">{c.code} · {c.branch.toUpperCase()}</div><h1>{c.title}</h1><p className="lead">{c.briefing}</p><div className="brief-grid"><div className="panel"><h3><ClipboardCheck size={18}/> Known information</h3>{c.facts.map(x=><div className="fact" key={x}>{x}</div>)}</div><div className="panel objective"><TriangleAlert size={26}/><h3>Your assignment</h3><p>Establish the most probable root cause. Inspect what is already known, order only defensible tests, use results to eliminate alternatives, then commit to one diagnosis.</p><div className="budget-big">{c.budget} <small>INVESTIGATION POINTS</small></div>{cp.bestScore>0&&<div className="prior-best">Previous best <b>{cp.bestScore}/100</b></div>}</div></div><div className="phase-note"><span>01</span> Observe & frame hypotheses <i/> <span>02</span> Test selectively <i/> <span>03</span> Diagnose <i/> <span>04</span> Consolidate what you learned</div><button className="primary" onClick={()=>setScreen('investigate')}>Enter investigation workspace <ArrowRight size={18}/></button></section></main>;

 if(screen==='report'&&result){const answer=c.hypotheses.find(x=>x.id===c.correct)!;const chosen=c.hypotheses.find(x=>x.id===hyp);return <main className="shell"><Header/><section className="report"><div className="eyebrow">FAILURE INVESTIGATION REPORT · {c.code} · {c.branch}</div><div className={'verdict '+(result.correct?'good':'bad')}><span>{result.correct?'ROOT CAUSE CONFIRMED':'DIAGNOSIS NOT SUPPORTED'}</span><strong>{result.total}</strong><small>/ 100</small></div><h1>{result.correct?answer.title:'Re-examine the evidence chain'}</h1><p className="lead">{result.correct?c.conclusion:`You selected “${chosen?.title||'—'}”. The evidence is more consistent with “${answer.title}”.`}</p><div className="score-grid five"><Score n={result.diagnosisScore} max={50} label="Diagnosis"/><Score n={result.evidenceScore} max={25} label="Evidence reasoning"/><Score n={result.investigationScore} max={15} label="Investigation"/><Score n={result.efficiencyScore} max={10} label="Efficiency"/><Score n={attemptUpdate?.iqGained||0} label="IQ gained"/></div><div className="report-grid"><div className="panel"><h3><ChartNoAxesCombined size={17}/> Why this diagnosis wins</h3><p>{c.conclusion}</p></div><div className="panel"><h3><ClipboardCheck size={17}/> Recommended response</h3><p>{c.response}</p></div></div><div className="learning-panel"><div><span>YOUR EVIDENCE COVERAGE</span><b>{result.criticalReviewed}/{result.criticalTotal}</b><small>critical findings reviewed</small></div><div><span>KEY INVESTIGATIONS</span><b>{result.keyTestsRun}/{result.keyTestsTotal}</b><small>high-value tests completed</small></div><div><span>BUDGET USED</span><b>{result.spent}/{c.budget}</b><small>investigation points</small></div><div><span>LOW-VALUE TESTS</span><b>{result.irrelevantTests}</b><small>ordered without diagnostic value</small></div></div><div className="panel lesson"><h3><Beaker size={17}/> What this case is teaching</h3><p>{c.lesson}</p></div>{notes&&<div className="panel note-report"><h3>Your investigation note</h3><p>{notes}</p></div>}<div className="mastery-line">{attemptUpdate?.newBest?<><Trophy size={16}/> New case best: <b>{result.total}/100</b></>:<>Case best: <b>{caseProgress(progress,c.code).bestScore}/100</b></>} {attemptUpdate&&attemptUpdate.iqGained===0&&<span>· No repeat IQ awarded unless you improve this case’s mastery.</span>}</div><div className="report-actions"><button className="primary" onClick={reset}>Investigate again</button><button className="ghost" onClick={()=>setScreen('home')}>Choose another case <ArrowRight size={16}/></button></div></section></main>}

 return <main className="workspace"><header className="work-head"><button className="icon" onClick={()=>setScreen('brief')}><ChevronLeft/></button><div><span>{c.code} · {c.branch.toUpperCase()} · INVESTIGATION ACTIVE</span><b>{c.title}</b></div><div className="budget"><small>IP REMAINING</small><strong>{c.budget-spent}</strong><span>/ {c.budget}</span></div></header><div className="work-grid"><section className="column"><Title icon={<Eye/>} title="Evidence locker" sub={`${reviewed.length} reviewed · ${unlocked.size}/${c.evidence.length} available`}/>{c.evidence.map(e=>{const open=unlocked.has(e.id);return <button key={e.id} disabled={!open} onClick={()=>review(e.id)} className={'evidence '+(reviewed.includes(e.id)?'seen':'')}><div>{open?<Eye size={16}/>:<span>—</span>}<b>{e.title}</b>{reviewed.includes(e.id)&&<Check size={15}/>}</div><p>{!open?'Locked — a relevant investigation may reveal this evidence.':e.detail}</p></button>})}</section><section className="column center"><Title icon={<Beaker/>} title="Technical subject" sub={c.subject}/><Subject c={c}/><div className="observation"><span>FIELD OBSERVATION 01</span><b>{c.observation}</b><p>Use observations to form hypotheses, not to skip the investigation. Strong conclusions should survive competing explanations.</p></div><Title icon={<FlaskConical/>} title="Investigation requests" sub={`${spent}/${c.budget} IP spent`}/>{c.tests.map(t=>{const done=tests.includes(t.id),cant=!done&&spent+t.cost>c.budget;return <div className="test" key={t.id}><div><b>{t.title}</b><span><Clock3 size={13}/>{t.time} · {t.cost} IP</span></div><button disabled={cant||done} onClick={()=>runTest(t.id)}>{done?'Completed':cant?'Insufficient IP':'Request'}</button>{done&&<p className="test-result"><Check size={14}/>{t.result}</p>}</div>})}</section><section className="column"><Title icon={<BookOpen/>} title="Competing hypotheses" sub="Commit to the best-supported root cause"/>{c.hypotheses.map(h=><button className={'hyp '+(hyp===h.id?'selected':'')} onClick={()=>setHyp(h.id)} key={h.id}><span className="radio">{hyp===h.id&&<i/>}</span><div><b>{h.title}</b><p>{h.description}</p></div></button>)}<label className="notes"><span><NotebookPen size={15}/> Investigator reasoning</span><textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="What evidence supports your choice? What evidence weakens the alternatives?"/></label><div className="submit-readiness"><span><Eye size={13}/>{reviewed.length} evidence reviewed</span><span><WalletCards size={13}/>{c.budget-spent} IP left</span></div><button className="submit" disabled={!hyp} onClick={submit}>Submit final diagnosis <ArrowRight size={17}/></button><small className="warning">You may submit early, but unexplored evidence will reduce the investigation score.</small></section></div></main>;
}

function Header(){return <header className="header"><div className="logo"><span>F</span><b>FAIL<span>LAB</span></b></div><div className="tag">BREAK IT · DIAGNOSE IT · UNDERSTAND IT</div></header>}
function Title({icon,title,sub}:{icon:ReactNode,title:string,sub:string}){return <div className="title"><span>{icon}</span><div><b>{title}</b><small>{sub}</small></div></div>}
function Score({n,max,label}:{n:number,max?:number,label:string}){return <div><strong>{n}{max&&<small>/{max}</small>}</strong><span>{label}</span></div>}
function Subject({c}:{c:FailureCase}){const symbol=c.code[0]==='C'?'△━━━━╱╱╱━━━━△':c.code[0]==='M'?'──◉══════╪════◉──':c.code[0]==='E'?'L1 ─ L2 ─ L3  ⚡  MOTOR':'> API → [ POOL ] → DB';return <div className="beam-wrap"><div className="load">{c.branch.toUpperCase()}</div><div className="subject-symbol">{symbol}</div><div className="dimension">{c.subject}</div></div>}
