import type {AppLanguage} from './preferences';

export type TranslationKey=
 |'gameEyebrow'|'heroTitle'|'heroQuestion'|'heroBody'|'yourProgress'|'engineeringIq'|'bestScore'|'dayStreak'|'casesSolved'
 |'syncingProgress'|'cloudSynced'|'signOut'|'signInGoogle'|'guestMode'|'chooseCase'|'pickBranch'|'cases'|'developerTrack'
 |'all'|'civil'|'mechanical'|'electrical'|'computerIt'|'allDev'|'webDev'|'backend'|'languages'
 |'solved'|'inProgress'|'new'|'aboutTime'|'best'|'playAgain'|'startCase'|'back'|'howToPlay'|'readClues'|'runUsefulTests'
 |'pickCause'|'seeWhy'|'yourGoal'|'goalBody'|'previousBest'|'startInvestigation'|'caseResult'|'foundRootCause'|'notQuite'
 |'correctDiagnosis'|'evidenceShows'|'youChose'|'strongestEvidence'|'correctCause'|'cluesUsed'|'tests'|'budget'|'iqGained'
 |'why'|'whatDone'|'mainLesson'|'tryAgain'|'chooseAnother'|'stepOf'|'budgetLeft'|'step1'|'step1Sub'|'whatYouSee'
 |'startHere'|'nextRunTests'|'openAllClues'|'step2'|'budgetUsed'|'testsHelp'|'budgetPoints'|'done'|'tooExpensive'
 |'runTest'|'backClues'|'nextChooseCause'|'step3'|'step3Sub'|'backTests'|'submitAnswer'|'afterSubmit'|'tagline';

type Dictionary=Record<TranslationKey,string>;

const en:Dictionary={
 gameEyebrow:'ENGINEERING FAILURE GAME',heroTitle:'Something failed.',heroQuestion:'Can you find out why?',heroBody:'Read the problem, inspect clues, run a few tests and choose the most likely cause. You do not need to be an expert — the game teaches you as you play.',yourProgress:'YOUR PROGRESS',engineeringIq:'ENGINEERING IQ',bestScore:'BEST SCORE',dayStreak:'DAY STREAK',casesSolved:'CASES SOLVED',syncingProgress:'Syncing progress…',cloudSynced:'Cloud progress synced',signOut:'Sign out',signInGoogle:'Sign in with Google',guestMode:'Guest mode · progress saved on this device',chooseCase:'CHOOSE A CASE',pickBranch:'Pick your engineering branch',cases:'CASES',developerTrack:'DEVELOPER TRACK',all:'All',civil:'Civil',mechanical:'Mechanical',electrical:'Electrical',computerIt:'Computer / IT',allDev:'All Dev',webDev:'Web Dev',backend:'Backend',languages:'Languages',solved:'SOLVED',inProgress:'IN PROGRESS',new:'NEW',aboutTime:'ABOUT 5–8 MIN',best:'BEST',playAgain:'Play again',startCase:'Start case',back:'Back',howToPlay:'How to play',readClues:'1. Read the clues',runUsefulTests:'2. Run useful tests using your budget',pickCause:'3. Pick the most likely cause',seeWhy:'4. See why the answer is right or wrong',yourGoal:'Your goal',goalBody:'Find the most likely reason this failure happened. You have {budget} budget points for tests, so choose carefully.',previousBest:'Previous best',startInvestigation:'Start investigation',caseResult:'CASE RESULT',foundRootCause:'YOU FOUND THE ROOT CAUSE',notQuite:'NOT QUITE',correctDiagnosis:'Correct diagnosis',evidenceShows:'Here is what the evidence shows',youChose:'You chose “{chosen}”.',strongestEvidence:'The strongest evidence supports “{answer}”.',correctCause:'Correct cause',cluesUsed:'Clues used',tests:'Tests',budget:'Budget',iqGained:'IQ gained',why:'Why?',whatDone:'What should be done?',mainLesson:'Main lesson',tryAgain:'Try again',chooseAnother:'Choose another case',stepOf:'STEP {step} OF 3',budgetLeft:'BUDGET LEFT',step1:'Step 1 — Check the clues',step1Sub:'Tap each clue to mark it as reviewed',whatYouSee:'WHAT YOU SEE',startHere:'Start here, then open the clues below.',nextRunTests:'Next: run tests',openAllClues:'Open all available clues first.',step2:'Step 2 — Run useful tests',budgetUsed:'Budget used {spent}/{budget}',testsHelp:'Tests can reveal hidden clues. You do not need to run every test. Try to spend your budget only on tests that help rule causes in or out.',budgetPoints:'budget points',done:'Done',tooExpensive:'Too expensive',runTest:'Run test',backClues:'Back to clues',nextChooseCause:'Next: choose a cause',step3:'Step 3 — Choose the cause',step3Sub:'Pick the explanation best supported by the clues and tests',backTests:'Back to tests',submitAnswer:'Submit answer',afterSubmit:'After submitting, the game will explain the correct reasoning.',tagline:'FIND THE FAILURE · LEARN THE WHY'
};

const hi:Dictionary={
 gameEyebrow:'इंजीनियरिंग फेल्योर गेम',heroTitle:'कुछ खराब हुआ है।',heroQuestion:'क्या आप कारण ढूँढ सकते हैं?',heroBody:'समस्या पढ़ें, सुराग देखें, कुछ टेस्ट चलाएँ और सबसे संभावित कारण चुनें। विशेषज्ञ होना ज़रूरी नहीं — खेलते-खेलते आप सीखेंगे।',yourProgress:'आपकी प्रगति',engineeringIq:'इंजीनियरिंग IQ',bestScore:'सर्वश्रेष्ठ स्कोर',dayStreak:'दिनों की स्ट्रीक',casesSolved:'हल किए केस',syncingProgress:'प्रगति सिंक हो रही है…',cloudSynced:'क्लाउड प्रगति सिंक हो गई',signOut:'साइन आउट',signInGoogle:'Google से साइन इन करें',guestMode:'गेस्ट मोड · प्रगति इस डिवाइस पर सेव है',chooseCase:'केस चुनें',pickBranch:'अपनी इंजीनियरिंग शाखा चुनें',cases:'केस',developerTrack:'डेवलपर ट्रैक',all:'सभी',civil:'सिविल',mechanical:'मैकेनिकल',electrical:'इलेक्ट्रिकल',computerIt:'कंप्यूटर / IT',allDev:'सभी Dev',webDev:'वेब Dev',backend:'बैकएंड',languages:'भाषाएँ',solved:'हल',inProgress:'जारी',new:'नया',aboutTime:'लगभग 5–8 मिनट',best:'बेस्ट',playAgain:'फिर खेलें',startCase:'केस शुरू करें',back:'वापस',howToPlay:'कैसे खेलें',readClues:'1. सुराग पढ़ें',runUsefulTests:'2. बजट का उपयोग करके ज़रूरी टेस्ट चलाएँ',pickCause:'3. सबसे संभावित कारण चुनें',seeWhy:'4. देखें उत्तर सही या गलत क्यों है',yourGoal:'आपका लक्ष्य',goalBody:'इस विफलता का सबसे संभावित कारण खोजें। टेस्ट के लिए आपके पास {budget} बजट पॉइंट हैं, इसलिए सोच-समझकर चुनें।',previousBest:'पिछला बेस्ट',startInvestigation:'जाँच शुरू करें',caseResult:'केस परिणाम',foundRootCause:'आपने मूल कारण ढूँढ लिया',notQuite:'अभी सही नहीं',correctDiagnosis:'सही निदान',evidenceShows:'सबूत यह दिखाते हैं',youChose:'आपने “{chosen}” चुना।',strongestEvidence:'सबसे मजबूत सबूत “{answer}” का समर्थन करते हैं।',correctCause:'सही कारण',cluesUsed:'इस्तेमाल किए सुराग',tests:'टेस्ट',budget:'बजट',iqGained:'मिला IQ',why:'क्यों?',whatDone:'क्या करना चाहिए?',mainLesson:'मुख्य सीख',tryAgain:'फिर कोशिश करें',chooseAnother:'दूसरा केस चुनें',stepOf:'स्टेप {step} / 3',budgetLeft:'बाकी बजट',step1:'स्टेप 1 — सुराग देखें',step1Sub:'हर सुराग को पढ़ने के लिए टैप करें',whatYouSee:'आप क्या देख रहे हैं',startHere:'यहाँ से शुरू करें, फिर नीचे के सुराग खोलें।',nextRunTests:'अगला: टेस्ट चलाएँ',openAllClues:'पहले सभी उपलब्ध सुराग खोलें।',step2:'स्टेप 2 — उपयोगी टेस्ट चलाएँ',budgetUsed:'बजट उपयोग {spent}/{budget}',testsHelp:'टेस्ट छिपे हुए सुराग दिखा सकते हैं। हर टेस्ट चलाना ज़रूरी नहीं है। केवल वही टेस्ट चुनें जो कारण को साबित या खारिज करने में मदद करें।',budgetPoints:'बजट पॉइंट',done:'पूरा',tooExpensive:'बहुत महँगा',runTest:'टेस्ट चलाएँ',backClues:'सुरागों पर वापस',nextChooseCause:'अगला: कारण चुनें',step3:'स्टेप 3 — कारण चुनें',step3Sub:'सुराग और टेस्ट से सबसे अच्छी तरह समर्थित कारण चुनें',backTests:'टेस्ट पर वापस',submitAnswer:'उत्तर जमा करें',afterSubmit:'जमा करने के बाद खेल सही कारण समझाएगा।',tagline:'विफलता खोजें · कारण समझें'
};

const mr:Dictionary={
 gameEyebrow:'इंजिनिअरिंग फेल्युअर गेम',heroTitle:'काहीतरी बिघडलं आहे.',heroQuestion:'का बिघडलं ते शोधू शकता का?',heroBody:'समस्या वाचा, सुगावे तपासा, काही टेस्ट करा आणि सर्वात शक्य कारण निवडा. तज्ज्ञ असण्याची गरज नाही — खेळताना तुम्ही शिकाल.',yourProgress:'तुमची प्रगती',engineeringIq:'इंजिनिअरिंग IQ',bestScore:'सर्वोत्तम स्कोअर',dayStreak:'दिवसांची स्ट्रीक',casesSolved:'सोडवलेले केस',syncingProgress:'प्रगती सिंक होत आहे…',cloudSynced:'क्लाउड प्रगती सिंक झाली',signOut:'साइन आउट',signInGoogle:'Google ने साइन इन करा',guestMode:'गेस्ट मोड · प्रगती या डिव्हाइसवर सेव आहे',chooseCase:'केस निवडा',pickBranch:'तुमची इंजिनिअरिंग शाखा निवडा',cases:'केस',developerTrack:'डेव्हलपर ट्रॅक',all:'सर्व',civil:'सिविल',mechanical:'मेकॅनिकल',electrical:'इलेक्ट्रिकल',computerIt:'कंप्युटर / IT',allDev:'सर्व Dev',webDev:'वेब Dev',backend:'बॅकएंड',languages:'भाषा',solved:'सोडवला',inProgress:'सुरू',new:'नवीन',aboutTime:'सुमारे 5–8 मिनिटे',best:'बेस्ट',playAgain:'पुन्हा खेळा',startCase:'केस सुरू करा',back:'मागे',howToPlay:'कसे खेळायचे',readClues:'1. सुगावे वाचा',runUsefulTests:'2. बजेट वापरून उपयोगी टेस्ट करा',pickCause:'3. सर्वात शक्य कारण निवडा',seeWhy:'4. उत्तर बरोबर किंवा चूक का आहे ते पहा',yourGoal:'तुमचे ध्येय',goalBody:'ही समस्या का झाली याचे सर्वात शक्य कारण शोधा. टेस्टसाठी तुमच्याकडे {budget} बजेट पॉइंट आहेत, त्यामुळे योग्य निवड करा.',previousBest:'मागील बेस्ट',startInvestigation:'तपास सुरू करा',caseResult:'केस निकाल',foundRootCause:'तुम्ही मूळ कारण शोधले',notQuite:'अजून बरोबर नाही',correctDiagnosis:'योग्य निदान',evidenceShows:'पुरावे हे दाखवतात',youChose:'तुम्ही “{chosen}” निवडले.',strongestEvidence:'सर्वात मजबूत पुरावे “{answer}” ला समर्थन देतात.',correctCause:'योग्य कारण',cluesUsed:'वापरलेले सुगावे',tests:'टेस्ट',budget:'बजेट',iqGained:'मिळालेला IQ',why:'का?',whatDone:'काय केले पाहिजे?',mainLesson:'मुख्य शिकवण',tryAgain:'पुन्हा प्रयत्न करा',chooseAnother:'दुसरा केस निवडा',stepOf:'स्टेप {step} / 3',budgetLeft:'उरलेले बजेट',step1:'स्टेप 1 — सुगावे तपासा',step1Sub:'प्रत्येक सुगावा पाहण्यासाठी टॅप करा',whatYouSee:'तुम्हाला काय दिसते',startHere:'इथून सुरू करा, मग खालील सुगावे उघडा.',nextRunTests:'पुढे: टेस्ट करा',openAllClues:'आधी सर्व उपलब्ध सुगावे उघडा.',step2:'स्टेप 2 — उपयोगी टेस्ट करा',budgetUsed:'वापरलेले बजेट {spent}/{budget}',testsHelp:'टेस्टमुळे लपलेले सुगावे मिळू शकतात. प्रत्येक टेस्ट करणे आवश्यक नाही. कारण ठरवायला मदत करणाऱ्या टेस्टच निवडा.',budgetPoints:'बजेट पॉइंट',done:'पूर्ण',tooExpensive:'खूप महाग',runTest:'टेस्ट करा',backClues:'सुगाव्यांकडे मागे',nextChooseCause:'पुढे: कारण निवडा',step3:'स्टेप 3 — कारण निवडा',step3Sub:'सुगावे आणि टेस्टने सर्वाधिक समर्थित कारण निवडा',backTests:'टेस्टकडे मागे',submitAnswer:'उत्तर सबमिट करा',afterSubmit:'सबमिट केल्यानंतर गेम योग्य कारण समजावेल.',tagline:'बिघाड शोधा · कारण समजा'
};

const dictionaries:Record<AppLanguage,Dictionary>={en,hi,mr};

export function translate(language:AppLanguage,key:TranslationKey,vars:Record<string,string|number>={}){
 let value=dictionaries[language][key]??en[key];
 for(const [name,replacement] of Object.entries(vars)) value=value.replaceAll(`{${name}}`,String(replacement));
 return value;
}
