import {useEffect,useMemo,useState} from 'react';
import {Eye,ScanSearch,ShieldCheck,TriangleAlert,X} from 'lucide-react';
import CaseFigure from './CaseFigure';
import {usePreferences} from './preferences';
import './InteractiveCaseFigure.css';

type Lang='en'|'hi'|'mr';
type Props={code:string;compact?:boolean};
type LocalText=Record<Lang,string>;
type Hotspot={x:number;y:number;label:LocalText;detail:LocalText};
type CaseInteraction={hotspots:Hotspot[];normal:LocalText;fault:LocalText};

const L=(en:string,hi:string,mr:string):LocalText=>({en,hi,mr});
const H=(x:number,y:number,label:LocalText,detail:LocalText):Hotspot=>({x,y,label,detail});

const ui={
 inspect:L('Inspect figure','चित्र देखें','आकृती तपासा'),
 hint:L('Tap the marker to inspect the suspicious area.','संदिग्ध जगह देखने के लिए marker पर tap करें।','संशयित भाग पाहण्यासाठी marker वर tap करा.'),
 normal:L('Normal','सामान्य','सामान्य'),
 fault:L('Fault view','Fault view','Fault view'),
 selected:L('INSPECTED AREA','जाँचा गया भाग','तपासलेला भाग'),
 close:L('Close','बंद करें','बंद करा')
} satisfies Record<string,LocalText>;

const interactions:Record<string,CaseInteraction>={
 'C-001':{hotspots:[H(52,72,L('Mid-span cracks','बीच की दरारें','मध्यभागी भेगा'),L('Several vertical cracks are concentrated near mid-span, where bending is highest.','कई vertical cracks beam के बीच में हैं, जहाँ bending सबसे अधिक होती है।','अनेक उभ्या भेगा beam च्या मध्यभागी आहेत, जिथे bending सर्वाधिक असते.'))],normal:L('A healthy beam carries its design load without wide mid-span flexural cracks.','सही beam design load पर बड़ी mid-span cracks नहीं दिखाती।','निरोगी beam design load वर मोठ्या mid-span भेगा दाखवत नाही.'),fault:L('The actual floor load is much higher than the design load, making these cracks important.','Actual load design load से काफी ज्यादा है, इसलिए ये cracks महत्वपूर्ण हैं।','Actual load design load पेक्षा जास्त असल्यामुळे या भेगा महत्त्वाच्या आहेत.')},
 'C-002':{hotspots:[H(77,80,L('Wet soil zone','गीली मिट्टी','ओलसर माती'),L('Water is collecting beside the footing and softening the supporting soil.','Footing के पास पानी जमा होकर soil को soft कर रहा है।','Footing जवळ पाणी साचून soil मऊ होत आहे.'))],normal:L('A foundation needs firm, uniformly supporting soil and controlled drainage.','Foundation के नीचे firm soil और proper drainage चाहिए।','Foundation खाली firm soil आणि योग्य drainage आवश्यक आहे.'),fault:L('Localized wet soil can lose stiffness and allow one part of the footing to settle.','Localized wet soil stiffness खो सकती है और footing का एक हिस्सा बैठ सकता है।','Localized ओलसर soil stiffness गमावून footing चा एक भाग खाली बसू शकतो.')},
 'C-003':{hotspots:[H(81,59,L('Construction joint','Construction joint','Construction joint'),L('The leak follows the horizontal construction joint, a common weak path if the waterstop is poor or missing.','Leak horizontal construction joint के along है; poor/missing waterstop यहाँ weak path बनाता है।','Leak horizontal construction joint वर आहे; poor/missing waterstop मुळे येथे weak path तयार होतो.'))],normal:L('A watertight joint prevents stored water from crossing the concrete lift interface.','Watertight joint पानी को concrete lift interface से बाहर नहीं जाने देता।','Watertight joint पाणी concrete lift interface मधून बाहेर जाऊ देत नाही.'),fault:L('A defective joint creates a continuous leakage path even when the surrounding concrete is sound.','Defective joint surrounding concrete ठीक होने पर भी continuous leak path बनाता है।','Defective joint मुळे आसपासचे concrete चांगले असतानाही सतत leakage path तयार होतो.')},
 'M-001':{hotspots:[H(48,54,L('Keyway root','Keyway root','Keyway root'),L('The keyway root concentrates stress. Repeated loading can start a fatigue crack here.','Keyway root पर stress concentration होता है और repeated loading fatigue crack शुरू कर सकती है।','Keyway root येथे stress concentration होतो आणि repeated loading मुळे fatigue crack सुरू होऊ शकतो.'))],normal:L('A well-aligned shaft distributes cyclic stress without a sharp local concentration.','Well-aligned shaft cyclic stress को evenly distribute करता है।','Well-aligned shaft cyclic stress समप्रमाणात वितरित करतो.'),fault:L('Misalignment plus the keyway stress concentration accelerates fatigue growth.','Misalignment और keyway stress concentration fatigue growth को तेज करते हैं।','Misalignment आणि keyway stress concentration मुळे fatigue growth वेगाने होते.')},
 'M-002':{hotspots:[H(70,36,L('Hot bearing','गर्म bearing','गरम bearing'),L('The bearing is running near 92°C. Excess grease can churn, create drag and raise temperature.','Bearing लगभग 92°C है। Excess grease churning और drag बढ़ाकर temperature बढ़ा सकती है।','Bearing सुमारे 92°C आहे. Excess grease churning आणि drag वाढवून temperature वाढवू शकते.'))],normal:L('Correct grease quantity forms a thin lubricating film with low drag.','Correct grease quantity low drag के साथ lubricating film बनाती है।','योग्य grease quantity कमी drag सह lubricating film तयार करते.'),fault:L('Too much grease is not extra protection; it can make the bearing run hotter.','बहुत ज्यादा grease extra protection नहीं है; bearing और गर्म हो सकती है।','खूप grease म्हणजे extra protection नाही; bearing अधिक गरम होऊ शकते.')},
 'M-003':{hotspots:[H(78,56,L('Coupling offset','Coupling offset','Coupling offset'),L('The connected shafts are offset, creating strong 1× running-speed vibration.','Connected shafts offset हैं, जिससे strong 1× running-speed vibration बनती है।','Connected shafts offset असल्यामुळे strong 1× running-speed vibration निर्माण होते.'))],normal:L('Aligned shafts share one centerline through the coupling.','Aligned shafts coupling के through एक centerline share करते हैं।','Aligned shafts coupling मधून एकच centerline share करतात.'),fault:L('Offset misalignment repeatedly loads bearings and the gearbox once per revolution.','Offset misalignment हर revolution में bearings और gearbox को load करती है।','Offset misalignment प्रत्येक revolution ला bearings आणि gearbox वर load टाकते.')},
 'E-001':{hotspots:[H(39,31,L('Hot terminal','गर्म terminal','गरम terminal'),L('One terminal is much hotter than the others, pointing to local resistance rather than whole-motor overload.','एक terminal बाकी से ज्यादा गर्म है, जो whole-motor overload के बजाय local resistance दिखाता है।','एक terminal इतरांपेक्षा जास्त गरम आहे, म्हणजे whole-motor overload पेक्षा local resistance ची शक्यता जास्त आहे.'))],normal:L('Healthy phase terminals have tight, low-resistance connections and similar temperatures.','Healthy phase terminals tight होते हैं और temperature लगभग समान रहता है।','Healthy phase terminals tight असतात आणि temperature जवळपास समान राहतो.'),fault:L('A loose/high-resistance connection converts electrical power into heat at one terminal.','Loose/high-resistance connection एक terminal पर electrical power को heat में बदलता है।','Loose/high-resistance connection मुळे एका terminal वर electrical power heat मध्ये बदलते.')},
 'E-002':{hotspots:[H(50,44,L('Inrush spike','Inrush spike','Inrush spike'),L('Both motors starting together can stack their inrush currents and momentarily exceed the breaker curve.','दोनों motors साथ start होने से inrush currents जुड़कर breaker curve exceed कर सकती हैं।','दोन्ही motors एकत्र start झाल्यास inrush currents मिळून breaker curve exceed करू शकतात.'))],normal:L('Staggered starts keep peak current within the breaker’s short-time tolerance.','Staggered starts peak current को breaker tolerance के अंदर रखती हैं।','Staggered starts peak current breaker tolerance मध्ये ठेवतात.'),fault:L('Simultaneous starting creates a brief current peak even though normal running current is acceptable.','Simultaneous start brief current peak बनाता है, भले running current normal हो।','Simultaneous start मुळे brief current peak तयार होतो, जरी running current normal असला तरी.')},
 'E-003':{hotspots:[H(50,84,L('Hot neutral','गर्म neutral','गरम neutral'),L('Triplen harmonics from nonlinear loads add in the neutral instead of cancelling.','Nonlinear loads के triplen harmonics neutral में cancel होने के बजाय add होते हैं।','Nonlinear loads चे triplen harmonics neutral मध्ये cancel न होता add होतात.'))],normal:L('Balanced sinusoidal phase currents largely cancel in the neutral.','Balanced sinusoidal phase currents neutral में largely cancel होती हैं।','Balanced sinusoidal phase currents neutral मध्ये largely cancel होतात.'),fault:L('3rd-harmonic current can make the neutral and transformer hotter than expected.','3rd-harmonic current neutral और transformer को expected से ज्यादा गर्म कर सकती है।','3rd-harmonic current neutral आणि transformer अपेक्षेपेक्षा जास्त गरम करू शकतो.')},
 'T-001':{hotspots:[H(77,50,L('Connection pool full','Connection pool full','Connection pool full'),L('All database connections are occupied, so new API requests wait even if CPU is still available.','सभी DB connections busy हैं, इसलिए CPU available होने पर भी new API requests wait करती हैं।','सर्व DB connections busy असल्यामुळे CPU available असतानाही new API requests wait करतात.'))],normal:L('Healthy traffic returns DB connections quickly enough for the pool to keep circulating.','Healthy traffic में DB connections जल्दी return होती हैं और pool circulate करता रहता है।','Healthy traffic मध्ये DB connections लवकर return होतात आणि pool circulate होत राहतो.'),fault:L('At 10/10 active connections, incoming requests queue and latency climbs sharply.','10/10 active connections पर requests queue होती हैं और latency तेजी से बढ़ती है।','10/10 active connections वर requests queue होतात आणि latency झपाट्याने वाढते.')},
 'T-002':{hotspots:[H(30,45,L('Sequential scan','Sequential scan','Sequential scan'),L('LOWER(email) changes the expression, so a plain email index may not be usable.','LOWER(email) expression बदलता है, इसलिए plain email index usable नहीं हो सकता।','LOWER(email) expression बदलतो, त्यामुळे plain email index usable नसू शकतो.'))],normal:L('An index matching the searched expression lets the database jump to a tiny set of rows.','Matching index database को सीधे few rows पर jump करने देता है।','Matching index database ला थेट काही rows वर jump करू देतो.'),fault:L('Without a functional index, the query can scan millions of rows for every lookup.','Functional index के बिना query हर lookup में millions of rows scan कर सकती है।','Functional index नसल्यास query प्रत्येक lookup ला millions of rows scan करू शकते.')},
 'T-003':{hotspots:[H(73,54,L('Unbounded cache','Unbounded cache','Unbounded cache'),L('The Map keeps accumulating entries and does not release old values, so heap usage rises over time.','Map entries जमा करती रहती है और old values release नहीं करती, इसलिए heap बढ़ता रहता है।','Map entries साठवत राहतो आणि old values release करत नाही, त्यामुळे heap वाढत राहतो.'))],normal:L('A bounded cache evicts old entries so memory settles around a stable level.','Bounded cache old entries evict करती है और memory stable रहती है।','Bounded cache old entries evict करतो आणि memory stable राहते.'),fault:L('An ever-growing cache produces the classic staircase memory-leak pattern.','Ever-growing cache classic staircase memory-leak pattern बनाती है।','Ever-growing cache classic staircase memory-leak pattern तयार करतो.')},
 'T-004':{hotspots:[H(50,52,L('HTML mismatch','HTML mismatch','HTML mismatch'),L('Server and client render different text for the same initial UI, so React cannot hydrate cleanly.','Server और client initial UI के लिए अलग text render करते हैं, इसलिए React hydration clean नहीं होती।','Server आणि client initial UI साठी वेगळा text render करतात, त्यामुळे React hydration clean होत नाही.'))],normal:L('Server HTML and the client’s first render must match exactly.','Server HTML और client का first render exactly match होना चाहिए।','Server HTML आणि client चा first render exactly match झाला पाहिजे.'),fault:L('Time/random/browser-only values can make the first client render differ by even one character.','Time/random/browser-only values first client render को एक character तक अलग कर सकती हैं।','Time/random/browser-only values first client render ला अगदी एका character नेही वेगळे करू शकतात.')},
 'T-005':{hotspots:[H(50,50,L('Render cycle','Render cycle','Render cycle'),L('An effect updates state, that update causes another render, and the effect runs again.','Effect state update करता है, उससे फिर render होता है और effect फिर चलता है।','Effect state update करतो, त्यामुळे पुन्हा render होतो आणि effect पुन्हा चालतो.'))],normal:L('An effect should run only when its true dependencies change, not after every state update it creates.','Effect केवल real dependencies change होने पर चलना चाहिए।','Effect फक्त real dependencies बदलल्यावर चालला पाहिजे.'),fault:L('A missing/unstable dependency guard can create render → effect → setState forever.','Missing/unstable dependency guard render → effect → setState loop बना सकती है।','Missing/unstable dependency guard render → effect → setState loop तयार करू शकते.')},
 'T-006':{hotspots:[H(67,51,L('Viewport setup','Viewport setup','Viewport setup'),L('Without the correct viewport behavior, mobile browsers can lay out the page like a wide desktop canvas.','Correct viewport के बिना mobile browser page को wide desktop canvas जैसा layout कर सकता है।','Correct viewport नसल्यास mobile browser page ला wide desktop canvas सारखा layout करू शकतो.'))],normal:L('A responsive viewport maps CSS pixels to the actual device width.','Responsive viewport CSS pixels को actual device width से map करता है।','Responsive viewport CSS pixels ला actual device width शी map करतो.'),fault:L('The result looks zoomed-out or over-wide even when the CSS breakpoints seem correct.','Result zoomed-out/over-wide दिख सकता है, even if CSS breakpoints correct हों।','CSS breakpoints correct असतानाही result zoomed-out/over-wide दिसू शकतो.')},
 'T-007':{hotspots:[H(57,59,L('Different JWT secret','अलग JWT secret','वेगळा JWT secret'),L('A token signed on Server A fails when Server B verifies it with a different secret.','Server A का signed token Server B पर different secret से verify नहीं होता।','Server A वर signed token Server B वर different secret मुळे verify होत नाही.'))],normal:L('All instances that verify the same JWTs need a consistent signing/verification configuration.','Same JWT verify करने वाले सभी instances की signing config consistent होनी चाहिए।','Same JWT verify करणाऱ्या सर्व instances ची signing config consistent असली पाहिजे.'),fault:L('Load balancing makes the bug intermittent: requests work on one server and return 401 on another.','Load balancing bug को intermittent बनाती है: एक server पर works, दूसरे पर 401।','Load balancing मुळे bug intermittent होतो: एका server वर works, दुसऱ्यावर 401.')},
 'T-008':{hotspots:[H(75,64,L('Double insert','Double insert','Double insert'),L('Two requests both see “no order” before either insert commits, so both create a row.','दो requests दोनों “no order” देखते हैं और दोनों insert कर देते हैं।','दोन requests दोन्ही “no order” पाहतात आणि दोन्ही insert करतात.'))],normal:L('A unique constraint or atomic transaction lets only one order win the race.','Unique constraint/atomic transaction race में केवल one order को succeed होने देती है।','Unique constraint/atomic transaction race मध्ये फक्त one order ला succeed होऊ देते.'),fault:L('Check-then-insert without DB protection is vulnerable to concurrent requests.','DB protection के बिना check-then-insert concurrent requests में unsafe है।','DB protection शिवाय check-then-insert concurrent requests मध्ये unsafe आहे.')},
 'T-009':{hotspots:[H(76,49,L('Blocking CPU work','Blocking CPU work','Blocking CPU work'),L('A synchronous CPU-heavy job occupies the Node.js event loop, delaying unrelated requests.','Synchronous CPU-heavy job Node.js event loop को block करके unrelated requests delay करती है।','Synchronous CPU-heavy job Node.js event loop block करून unrelated requests delay करतो.'))],normal:L('The event loop should stay free to process callbacks while heavy work moves off the main thread/path.','Event loop callbacks के लिए free रहना चाहिए और heavy work main path से बाहर होना चाहिए।','Event loop callbacks साठी free राहिला पाहिजे आणि heavy work main path बाहेर गेला पाहिजे.'),fault:L('One long synchronous task can freeze many users at once.','एक long synchronous task कई users को एक साथ freeze कर सकती है।','एक long synchronous task अनेक users ना एकाच वेळी freeze करू शकतो.')},
 'T-010':{hotspots:[H(78,50,L('Shared default list','Shared default list','Shared default list'),L('Python creates the default list once, so later calls reuse the same mutable object.','Python default list एक बार बनाता है, इसलिए later calls उसी mutable object को reuse करती हैं।','Python default list एकदाच तयार करतो, त्यामुळे later calls तोच mutable object reuse करतात.'))],normal:L('Use None as the default and create a new list inside the function for each call.','Default में None use करें और हर call में नई list बनाएं।','Default म्हणून None वापरा आणि प्रत्येक call साठी function मध्ये नवी list तयार करा.'),fault:L('The shared list keeps data from previous calls, which looks like values are appearing “by themselves”.','Shared list previous calls का data रखती है, इसलिए values अपने आप आती हुई लगती हैं।','Shared list previous calls चा data ठेवते, त्यामुळे values स्वतःहून येत असल्यासारख्या दिसतात.')}
};

export default function InteractiveCaseFigure({code,compact=false}:Props){
 const {language}=usePreferences();
 const lang=language as Lang;
 const config=interactions[code];
 const [active,setActive]=useState<number|null>(null);
 const [mode,setMode]=useState<'fault'|'normal'>('fault');
 const [inspect,setInspect]=useState(false);
 useEffect(()=>{setActive(null);setMode('fault');setInspect(false)},[code]);
 const spot=useMemo(()=>active===null?null:config?.hotspots[active]||null,[active,config]);
 if(!config)return <CaseFigure code={code} compact={compact}/>;
 return <div className={'interactive-case-figure '+mode+'-view '+(inspect?'inspect-on':'')}>
  <div className="icf-stage">
   <CaseFigure code={code} compact={compact}/>
   {inspect&&<div className="icf-hotspot-layer" aria-label={ui.inspect[lang]}>{config.hotspots.map((h,i)=><button key={i} type="button" className={'icf-hotspot '+(active===i?'active':'')} style={{left:`${h.x}%`,top:`${h.y}%`}} onClick={()=>setActive(i)} aria-label={h.label[lang]}><span>{i+1}</span></button>)}</div>}
  </div>
  <div className="icf-toolbar">
   <button type="button" className={'icf-inspect '+(inspect?'active':'')} onClick={()=>{setInspect(v=>!v);if(inspect)setActive(null)}}><ScanSearch size={15}/>{ui.inspect[lang]}</button>
   <div className="icf-toggle" role="group" aria-label="Figure comparison">
    <button className={mode==='normal'?'active':''} onClick={()=>setMode('normal')}><ShieldCheck size={14}/>{ui.normal[lang]}</button>
    <button className={mode==='fault'?'active':''} onClick={()=>setMode('fault')}><TriangleAlert size={14}/>{ui.fault[lang]}</button>
   </div>
  </div>
  {inspect&&!spot&&<div className="icf-hint"><Eye size={14}/>{ui.hint[lang]}</div>}
  {spot&&<div className="icf-detail" role="status"><div><span>{ui.selected[lang]}</span><b>{spot.label[lang]}</b><p>{spot.detail[lang]}</p></div><button onClick={()=>setActive(null)} aria-label={ui.close[lang]}><X size={16}/></button></div>}
  <div className={'icf-compare-note '+mode}><b>{mode==='normal'?ui.normal[lang]:ui.fault[lang]}</b><p>{(mode==='normal'?config.normal:config.fault)[lang]}</p></div>
 </div>;
}
